# Generated by Django 5.2.1 on 2026-02-09 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.TextField(help_text='AES-256 encrypted journal content')),
                ('sentiment_score', models.FloatField(blank=True, help_text='-1.0 (negative) to 1.0 (positive)', null=True)),
                ('stress_index', models.IntegerField(blank=True, help_text='0 (calm) to 10 (extreme stress)', null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='weather, temperature, location, tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
