# Generated by Django 5.2.1 on 2026-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_noteattachment_notification_timeslot_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='message_conv_read'),
        ),
        migrations.AddIndex(
            model_name='moodnote',
            index=models.Index(fields=['user', '-created_at'], name='moodnote_user_created'),
        ),
        migrations.AddIndex(
            model_name='moodnote',
            index=models.Index(fields=['user', 'sentiment_score'], name='moodnote_user_sentiment'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read'),
        ),
    ]
