# Generated by Codex on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_message_conv_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
