# Generated by Django 5.2.1 on 2026-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_avatar_customuser_token_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodnote',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='moodnote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
