# Generated by Django 5.2.1 on 2026-02-11 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_is_pinned_to_moodnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodnote',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='-1.0 (negative) to 1.0 (positive)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='moodnote',
            name='stress_index',
            field=models.IntegerField(blank=True, help_text='0 (calm) to 10 (extreme stress)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['counselor', 'date', 'status'], name='booking_counselor_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='message_sender_created'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['counselor', 'day_of_week', 'is_active'], name='timeslot_counselor_day'),
        ),
    ]
