# Generated by Django 5.2.1 on 2026-02-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aichatsession_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodnote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodnote',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moodnote',
            name='search_text',
            field=models.TextField(blank=True, default='', help_text='Plaintext index (first 500 chars) for DB-level search'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('note_create', 'Note Created'), ('note_update', 'Note Updated'), ('note_delete', 'Note Deleted'), ('note_restore', 'Note Restored'), ('account_delete', 'Account Deleted'), ('export_data', 'Data Exported')], max_length=30)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_user_created'), models.Index(fields=['action', '-created_at'], name='audit_action_created')],
            },
        ),
    ]
