# Generated by Django 5.2.1 on 2026-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message_type_metadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='conv_updated_at'),
        ),
        migrations.AddIndex(
            model_name='moodnote',
            index=models.Index(fields=['user', 'is_deleted'], name='moodnote_user_deleted'),
        ),
        migrations.AddIndex(
            model_name='sharednote',
            index=models.Index(fields=['shared_with', '-shared_at'], name='sharednote_user_date'),
        ),
    ]
