# Generated by Django 5.2.1 on 2026-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_missing_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='license_number',
            field=models.CharField(help_text='諮商師執照號碼', max_length=50, unique=True),
        ),
    ]
