# Generated by Django 5.2.1 on 2026-02-16 06:58

from django.db import migrations


ARTICLES = [
    {
        'title_zh': '認知扭曲入門',
        'title_en': 'Introduction to Cognitive Distortions',
        'title_ja': '認知の歪み入門',
        'content_zh': (
            '認知扭曲是我們思維中常見的偏差模式，會影響我們對事物的看法和情緒反應。\n\n'
            '## 常見的認知扭曲\n\n'
            '**1. 全有或全無思維**\n以非黑即白的方式看事情。例如：「如果我不能做到完美，那就是完全失敗。」\n\n'
            '**2. 過度概括**\n從單一事件得出廣泛結論。例如：「我這次考試沒考好，我永遠都學不好。」\n\n'
            '**3. 心理過濾**\n只關注負面細節，忽略正面的部分。\n\n'
            '**4. 妄下結論**\n在沒有充分證據的情況下做出負面判斷。\n\n'
            '**5. 災難化思維**\n把事情想像成最壞的情況。\n\n'
            '## 如何應對\n\n'
            '1. 覺察：注意自己的想法\n'
            '2. 質疑：「這個想法有證據支持嗎？」\n'
            '3. 替代：找到更平衡的想法\n'
            '4. 練習：反覆練習新的思維方式'
        ),
        'content_en': (
            'Cognitive distortions are common thinking patterns that can negatively affect how we perceive situations and react emotionally.\n\n'
            '## Common Cognitive Distortions\n\n'
            '**1. All-or-Nothing Thinking**\nSeeing things in black and white. Example: "If I\'m not perfect, I\'m a total failure."\n\n'
            '**2. Overgeneralization**\nDrawing broad conclusions from a single event. Example: "I failed this test, so I\'ll never learn."\n\n'
            '**3. Mental Filter**\nFocusing only on negative details while ignoring positive ones.\n\n'
            '**4. Jumping to Conclusions**\nMaking negative judgments without sufficient evidence.\n\n'
            '**5. Catastrophizing**\nImagining the worst possible outcome.\n\n'
            '## How to Cope\n\n'
            '1. Awareness: Notice your thoughts\n'
            '2. Challenge: "Is there evidence for this thought?"\n'
            '3. Replace: Find a more balanced thought\n'
            '4. Practice: Repeatedly practice new thinking patterns'
        ),
        'content_ja': (
            '認知の歪みとは、物事の見方や感情的な反応に影響を与える一般的な思考パターンです。\n\n'
            '## よくある認知の歪み\n\n'
            '**1. 全か無か思考**\n物事を白黒で見る。例：「完璧でなければ、完全な失敗だ。」\n\n'
            '**2. 過度の一般化**\n一つの出来事から広い結論を導く。例：「この試験に落ちたから、一生学べない。」\n\n'
            '**3. 心のフィルター**\nネガティブな部分だけに注目し、ポジティブな部分を無視する。\n\n'
            '**4. 結論の飛躍**\n十分な根拠なしにネガティブな判断をする。\n\n'
            '**5. 破局的思考**\n最悪の結果を想像する。\n\n'
            '## 対処法\n\n'
            '1. 気づき：自分の考えに気づく\n'
            '2. 疑問：「この考えを裏付ける証拠はあるか？」\n'
            '3. 置き換え：よりバランスの取れた考えを見つける\n'
            '4. 練習：新しい思考パターンを繰り返し練習する'
        ),
        'category': 'cbt',
        'reading_time': 5,
        'order': 1,
    },
    {
        'title_zh': '如何重新框架負面想法',
        'title_en': 'How to Reframe Negative Thoughts',
        'title_ja': 'ネガティブな考えをリフレーミングする方法',
        'content_zh': (
            '重新框架是認知行為治療（CBT）中的核心技巧，幫助你用更平衡的方式看待困難情境。\n\n'
            '## 步驟\n\n'
            '**1. 辨識自動化思考**\n當你感到不安時，問自己：「我現在在想什麼？」\n\n'
            '**2. 檢視證據**\n- 支持這個想法的證據是什麼？\n- 反對這個想法的證據是什麼？\n\n'
            '**3. 尋找替代觀點**\n- 如果朋友遇到同樣的情況，你會怎麼跟他們說？\n- 有沒有其他合理的解釋？\n\n'
            '**4. 評估結果**\n- 最壞的結果是什麼？我能應付嗎？\n- 最好的結果是什麼？\n- 最可能的結果是什麼？\n\n'
            '## 練習範例\n\n'
            '自動化思考：「我的報告一定會搞砸。」\n'
            '重新框架：「我已經準備了很多，即使不完美，也能呈現有價值的內容。」'
        ),
        'content_en': (
            'Reframing is a core technique in Cognitive Behavioral Therapy (CBT) that helps you see difficult situations in a more balanced way.\n\n'
            '## Steps\n\n'
            '**1. Identify Automatic Thoughts**\nWhen you feel upset, ask yourself: "What am I thinking right now?"\n\n'
            '**2. Examine the Evidence**\n- What evidence supports this thought?\n- What evidence contradicts it?\n\n'
            '**3. Find Alternative Perspectives**\n- What would you tell a friend in the same situation?\n- Are there other reasonable explanations?\n\n'
            '**4. Evaluate Outcomes**\n- What\'s the worst that could happen? Can I handle it?\n- What\'s the best outcome?\n- What\'s the most likely outcome?\n\n'
            '## Practice Example\n\n'
            'Automatic thought: "My presentation will be a disaster."\n'
            'Reframe: "I\'ve prepared thoroughly. Even if it\'s not perfect, I\'ll deliver valuable content."'
        ),
        'content_ja': (
            'リフレーミングは認知行動療法（CBT）の核心的な技法で、困難な状況をよりバランスの取れた方法で見るのに役立ちます。\n\n'
            '## ステップ\n\n'
            '**1. 自動思考を特定する**\n不安を感じたとき、自分に問いかけましょう：「今何を考えている？」\n\n'
            '**2. 証拠を検証する**\n- この考えを支持する証拠は？\n- この考えに反する証拠は？\n\n'
            '**3. 代替的な視点を探す**\n- 友達が同じ状況にいたら何と言いますか？\n- 他に合理的な説明はありますか？\n\n'
            '**4. 結果を評価する**\n- 最悪の結果は？対処できますか？\n- 最良の結果は？\n- 最も可能性の高い結果は？\n\n'
            '## 練習例\n\n'
            '自動思考：「プレゼンは絶対に失敗する。」\n'
            'リフレーミング：「十分に準備した。完璧でなくても、価値ある内容を伝えられる。」'
        ),
        'category': 'cbt',
        'reading_time': 5,
        'order': 2,
    },
    {
        'title_zh': '4-7-8 呼吸法',
        'title_en': '4-7-8 Breathing Technique',
        'title_ja': '4-7-8 呼吸法',
        'content_zh': (
            '4-7-8 呼吸法是由 Andrew Weil 醫師推廣的一種放鬆呼吸技巧，可以幫助減少焦慮和促進睡眠。\n\n'
            '## 步驟\n\n'
            '1. 舌尖抵住上門牙後方的牙齦\n'
            '2. 完全呼氣，發出呼的聲音\n'
            '3. 閉嘴，用鼻子安靜地吸氣，心中數到 **4**\n'
            '4. 屏住呼吸，心中數到 **7**\n'
            '5. 完全用嘴巴呼氣，發出呼的聲音，心中數到 **8**\n'
            '6. 這是一個循環。重複 3-4 個循環\n\n'
            '## 何時使用\n\n'
            '- 感到焦慮或緊張時\n'
            '- 睡前幫助入眠\n'
            '- 面對壓力情境前\n'
            '- 情緒激動需要冷靜時\n\n'
            '## 注意事項\n\n'
            '- 初學者可能會感到輕微頭暈，這是正常的\n'
            '- 如果屏住呼吸感到不適，可以先縮短時間\n'
            '- 建議每天練習兩次，持續至少 4-6 週'
        ),
        'content_en': (
            'The 4-7-8 breathing technique, popularized by Dr. Andrew Weil, is a relaxation method that helps reduce anxiety and promote sleep.\n\n'
            '## Steps\n\n'
            '1. Place the tip of your tongue behind your upper front teeth\n'
            '2. Exhale completely through your mouth with a whoosh sound\n'
            '3. Close your mouth, inhale quietly through your nose for a count of **4**\n'
            '4. Hold your breath for a count of **7**\n'
            '5. Exhale completely through your mouth with a whoosh for a count of **8**\n'
            '6. This is one cycle. Repeat 3-4 cycles\n\n'
            '## When to Use\n\n'
            '- When feeling anxious or tense\n'
            '- Before bed to help fall asleep\n'
            '- Before stressful situations\n'
            '- When you need to calm down from emotional intensity\n\n'
            '## Notes\n\n'
            '- Beginners may feel slightly dizzy — this is normal\n'
            '- If holding your breath is uncomfortable, shorten the duration first\n'
            '- Practice twice daily for at least 4-6 weeks for best results'
        ),
        'content_ja': (
            '4-7-8呼吸法は、アンドリュー・ワイル博士が普及させたリラクゼーション法で、不安を軽減し睡眠を促進するのに役立ちます。\n\n'
            '## ステップ\n\n'
            '1. 舌先を上の前歯の裏に当てる\n'
            '2. 口から完全に息を吐き出す\n'
            '3. 口を閉じ、鼻から静かに **4** つ数えながら息を吸う\n'
            '4. **7** つ数える間息を止める\n'
            '5. 口から **8** つ数えながら完全に息を吐く\n'
            '6. これが1サイクル。3-4サイクル繰り返す\n\n'
            '## 使用するタイミング\n\n'
            '- 不安や緊張を感じたとき\n'
            '- 就寝前の入眠サポート\n'
            '- ストレスの多い状況の前\n'
            '- 感情的に落ち着く必要があるとき\n\n'
            '## 注意点\n\n'
            '- 初心者は軽いめまいを感じることがあります（正常です）\n'
            '- 息を止めるのが辛い場合は時間を短くしましょう\n'
            '- 最良の結果を得るため、毎日2回、4-6週間続けましょう'
        ),
        'category': 'stress',
        'reading_time': 3,
        'order': 3,
    },
    {
        'title_zh': '5-4-3-2-1 接地練習',
        'title_en': '5-4-3-2-1 Grounding Exercise',
        'title_ja': '5-4-3-2-1 グラウンディングエクササイズ',
        'content_zh': (
            '5-4-3-2-1 接地技巧運用五感幫助你回到當下，特別適合在焦慮或恐慌發作時使用。\n\n'
            '## 練習方法\n\n'
            '深呼吸一次，然後：\n\n'
            '**5 — 看（視覺）**\n說出你能看到的 5 樣東西。\n\n'
            '**4 — 摸（觸覺）**\n說出你能觸摸到的 4 樣東西。\n\n'
            '**3 — 聽（聽覺）**\n說出你能聽到的 3 種聲音。\n\n'
            '**2 — 聞（嗅覺）**\n說出你能聞到的 2 種氣味。\n\n'
            '**1 — 嚐（味覺）**\n說出你能嚐到的 1 種味道。\n\n'
            '## 為什麼有效\n\n'
            '這個練習將注意力從焦慮的想法轉移到感官體驗上，幫助你的大腦回到當下的現實中。'
        ),
        'content_en': (
            'The 5-4-3-2-1 grounding technique uses your five senses to bring you back to the present moment, especially helpful during anxiety or panic attacks.\n\n'
            '## How to Practice\n\n'
            'Take a deep breath, then:\n\n'
            '**5 — See (Sight)**\nName 5 things you can see.\n\n'
            '**4 — Touch (Tactile)**\nName 4 things you can touch.\n\n'
            '**3 — Hear (Sound)**\nName 3 sounds you can hear.\n\n'
            '**2 — Smell (Olfactory)**\nName 2 things you can smell.\n\n'
            '**1 — Taste (Gustatory)**\nName 1 thing you can taste.\n\n'
            '## Why It Works\n\n'
            'This exercise shifts your attention from anxious thoughts to sensory experiences, helping your brain return to present reality.'
        ),
        'content_ja': (
            '5-4-3-2-1グラウンディングテクニックは、五感を使って今この瞬間に戻る方法で、不安やパニック発作時に特に有効です。\n\n'
            '## 練習方法\n\n'
            '深呼吸をしてから：\n\n'
            '**5 — 見る（視覚）**\n見えるものを5つ挙げる。\n\n'
            '**4 — 触る（触覚）**\n触れるものを4つ挙げる。\n\n'
            '**3 — 聞く（聴覚）**\n聞こえる音を3つ挙げる。\n\n'
            '**2 — 嗅ぐ（嗅覚）**\n匂いがするものを2つ挙げる。\n\n'
            '**1 — 味わう（味覚）**\n味がするものを1つ挙げる。\n\n'
            '## なぜ効果があるのか\n\n'
            'このエクササイズは不安な考えから感覚体験へ注意を移し、脳を現在の現実に戻すのに役立ちます。'
        ),
        'category': 'stress',
        'reading_time': 3,
        'order': 4,
    },
    {
        'title_zh': '情緒辨識與接納',
        'title_en': 'Emotion Identification and Acceptance',
        'title_ja': '感情の認識と受容',
        'content_zh': (
            '學會辨識和接納情緒是情緒智商的基礎，也是心理健康的重要一步。\n\n'
            '## 為什麼情緒辨識很重要\n\n'
            '- 當我們能準確命名情緒時，情緒的強度會自然降低\n'
            '- 辨識情緒幫助我們理解自己的需求\n'
            '- 它是有效溝通的基礎\n\n'
            '## 常見的情緒類別\n\n'
            '**基本情緒：** 快樂、悲傷、憤怒、恐懼、驚訝、厭惡\n\n'
            '**次要情緒：** 焦慮、嫉妒、羞恥、內疚、孤獨、感恩、希望\n\n'
            '## 練習步驟\n\n'
            '1. **暫停** — 注意到身體的感覺\n'
            '2. **命名** — 用具體的詞彙描述你的感受\n'
            '3. **接納** — 告訴自己：「有這個感覺是正常的」\n'
            '4. **探索** — 思考這個情緒在告訴你什麼\n'
            '5. **選擇** — 決定如何回應（而非反應）'
        ),
        'content_en': (
            'Learning to identify and accept emotions is the foundation of emotional intelligence and an important step toward mental health.\n\n'
            '## Why Emotion Identification Matters\n\n'
            '- When we can accurately name an emotion, its intensity naturally decreases\n'
            '- Identifying emotions helps us understand our needs\n'
            '- It\'s the foundation of effective communication\n\n'
            '## Common Emotion Categories\n\n'
            '**Basic emotions:** Joy, Sadness, Anger, Fear, Surprise, Disgust\n\n'
            '**Secondary emotions:** Anxiety, Jealousy, Shame, Guilt, Loneliness, Gratitude, Hope\n\n'
            '## Practice Steps\n\n'
            '1. **Pause** — Notice your bodily sensations\n'
            '2. **Name** — Use specific words to describe your feelings\n'
            '3. **Accept** — Tell yourself: "It\'s normal to feel this way"\n'
            '4. **Explore** — Consider what this emotion is telling you\n'
            '5. **Choose** — Decide how to respond (rather than react)'
        ),
        'content_ja': (
            '感情を認識し受け入れることは、感情知性の基礎であり、心の健康への重要なステップです。\n\n'
            '## なぜ感情の認識が重要か\n\n'
            '- 感情を正確に名前をつけられると、強度が自然に下がる\n'
            '- 感情を認識することは自分のニーズを理解するのに役立つ\n'
            '- 効果的なコミュニケーションの基礎\n\n'
            '## 一般的な感情カテゴリー\n\n'
            '**基本感情：** 喜び、悲しみ、怒り、恐れ、驚き、嫌悪\n\n'
            '**二次感情：** 不安、嫉妬、恥、罪悪感、孤独、感謝、希望\n\n'
            '## 練習ステップ\n\n'
            '1. **一時停止** — 体の感覚に気づく\n'
            '2. **名前をつける** — 具体的な言葉で感情を表現する\n'
            '3. **受け入れる** — 「こう感じるのは普通だ」と自分に言う\n'
            '4. **探求する** — この感情が何を伝えているか考える\n'
            '5. **選択する** — 反応ではなく、どう対応するか決める'
        ),
        'category': 'emotion',
        'reading_time': 5,
        'order': 5,
    },
    {
        'title_zh': '正念冥想入門',
        'title_en': 'Introduction to Mindfulness Meditation',
        'title_ja': 'マインドフルネス瞑想入門',
        'content_zh': (
            '正念是一種有意識地、不加評判地關注當下的練習。研究證明它能有效減少壓力、焦慮和憂鬱。\n\n'
            '## 基本正念呼吸練習（5分鐘）\n\n'
            '1. 找一個安靜舒適的地方坐下\n'
            '2. 閉上眼睛或輕輕低垂目光\n'
            '3. 將注意力放在呼吸上\n'
            '4. 注意吸氣和呼氣的感覺\n'
            '5. 當思緒飄走時，溫柔地帶回到呼吸上\n'
            '6. 不要評判自己的分心——這是正常的\n\n'
            '## 常見誤解\n\n'
            '- 正念不是「清空大腦」\n'
            '- 不需要完美地專注\n'
            '- 分心是練習的一部分\n'
            '- 不需要很長時間——每天 5 分鐘就很好\n\n'
            '## 融入日常\n\n'
            '- 正念吃飯：慢慢品嚐食物\n'
            '- 正念走路：感受每一步\n'
            '- 正念聆聽：完全專注在對方的話語上'
        ),
        'content_en': (
            'Mindfulness is the practice of intentionally paying attention to the present moment without judgment. Research shows it effectively reduces stress, anxiety, and depression.\n\n'
            '## Basic Mindful Breathing Exercise (5 minutes)\n\n'
            '1. Find a quiet, comfortable place to sit\n'
            '2. Close your eyes or gently lower your gaze\n'
            '3. Bring your attention to your breath\n'
            '4. Notice the sensation of inhaling and exhaling\n'
            '5. When your mind wanders, gently bring it back to the breath\n'
            '6. Don\'t judge your distraction — it\'s normal\n\n'
            '## Common Misconceptions\n\n'
            '- Mindfulness isn\'t about "emptying your mind"\n'
            '- You don\'t need to focus perfectly\n'
            '- Distraction is part of the practice\n'
            '- You don\'t need a lot of time — 5 minutes daily is great\n\n'
            '## Integrating into Daily Life\n\n'
            '- Mindful eating: Savor your food slowly\n'
            '- Mindful walking: Feel each step\n'
            '- Mindful listening: Fully focus on the other person\'s words'
        ),
        'content_ja': (
            'マインドフルネスとは、判断を加えずに意図的に今この瞬間に注意を向ける練習です。ストレス、不安、うつの軽減に効果があることが研究で示されています。\n\n'
            '## 基本的なマインドフル呼吸エクササイズ（5分）\n\n'
            '1. 静かで快適な場所に座る\n'
            '2. 目を閉じるか軽く視線を落とす\n'
            '3. 呼吸に注意を向ける\n'
            '4. 吸う時と吐く時の感覚に気づく\n'
            '5. 心がさまよったら、優しく呼吸に戻す\n'
            '6. 気が散ることを批判しない — それは普通のこと\n\n'
            '## よくある誤解\n\n'
            '- マインドフルネスは「心を空にする」ことではない\n'
            '- 完璧に集中する必要はない\n'
            '- 気が散ることは練習の一部\n'
            '- 長い時間は必要ない — 毎日5分で十分\n\n'
            '## 日常への統合\n\n'
            '- マインドフルな食事：食べ物をゆっくり味わう\n'
            '- マインドフルな歩行：一歩一歩を感じる\n'
            '- マインドフルな傾聴：相手の言葉に完全に集中する'
        ),
        'category': 'mindfulness',
        'reading_time': 5,
        'order': 6,
    },
    {
        'title_zh': '睡眠衛生指南',
        'title_en': 'Sleep Hygiene Guide',
        'title_ja': '睡眠衛生ガイド',
        'content_zh': (
            '良好的睡眠習慣對心理健康至關重要。以下是改善睡眠品質的實用建議。\n\n'
            '## 睡眠衛生原則\n\n'
            '**1. 固定作息**\n每天同一時間上床和起床，包括週末。\n\n'
            '**2. 創造良好睡眠環境**\n- 保持臥室涼爽、安靜、黑暗\n- 床只用來睡覺\n- 使用舒適的寢具\n\n'
            '**3. 睡前儀式**\n- 睡前 1 小時減少螢幕時間\n- 做放鬆活動：閱讀、泡澡、伸展\n- 避免刺激性內容\n\n'
            '**4. 飲食注意**\n- 下午 2 點後避免咖啡因\n- 睡前避免大量進食\n- 限制酒精攝取\n\n'
            '**5. 白天習慣**\n- 規律運動（但不要太接近睡覺時間）\n- 白天接觸自然光\n- 限制午睡在 20 分鐘以內\n\n'
            '## 如果睡不著\n\n'
            '如果躺在床上 20 分鐘還睡不著，起來做些放鬆的事，等到想睡了再回到床上。'
        ),
        'content_en': (
            'Good sleep habits are crucial for mental health. Here are practical tips to improve your sleep quality.\n\n'
            '## Sleep Hygiene Principles\n\n'
            '**1. Consistent Schedule**\nGo to bed and wake up at the same time every day, including weekends.\n\n'
            '**2. Optimize Your Sleep Environment**\n- Keep your bedroom cool, quiet, and dark\n- Use the bed only for sleeping\n- Use comfortable bedding\n\n'
            '**3. Bedtime Routine**\n- Reduce screen time 1 hour before bed\n- Do relaxing activities: reading, bathing, stretching\n- Avoid stimulating content\n\n'
            '**4. Diet Considerations**\n- Avoid caffeine after 2 PM\n- Avoid heavy meals before bed\n- Limit alcohol intake\n\n'
            '**5. Daytime Habits**\n- Exercise regularly (but not too close to bedtime)\n- Get natural light exposure during the day\n- Limit naps to 20 minutes\n\n'
            '## If You Can\'t Fall Asleep\n\n'
            'If you\'ve been lying in bed for 20 minutes and can\'t sleep, get up and do something relaxing. Return to bed when you feel sleepy.'
        ),
        'content_ja': (
            '良い睡眠習慣は心の健康に不可欠です。睡眠の質を改善するための実用的なアドバイスを紹介します。\n\n'
            '## 睡眠衛生の原則\n\n'
            '**1. 規則正しいスケジュール**\n週末を含め、毎日同じ時間に就寝・起床する。\n\n'
            '**2. 睡眠環境の最適化**\n- 寝室を涼しく、静かに、暗くする\n- ベッドは睡眠のみに使用する\n- 快適な寝具を使用する\n\n'
            '**3. 就寝前のルーティン**\n- 就寝1時間前にスクリーンタイムを減らす\n- リラックスする活動を行う：読書、入浴、ストレッチ\n- 刺激的なコンテンツを避ける\n\n'
            '**4. 食事の注意点**\n- 午後2時以降はカフェインを避ける\n- 就寝前の大量の食事を避ける\n- アルコール摂取を制限する\n\n'
            '**5. 日中の習慣**\n- 定期的に運動する（就寝直前は避ける）\n- 日中に自然光を浴びる\n- 昼寝は20分以内に制限\n\n'
            '## 眠れない場合\n\n'
            '20分間ベッドに横たわっても眠れない場合は、起きてリラックスできることをしましょう。眠くなったらベッドに戻りましょう。'
        ),
        'category': 'sleep',
        'reading_time': 5,
        'order': 7,
    },
    {
        'title_zh': '壓力管理策略',
        'title_en': 'Stress Management Strategies',
        'title_ja': 'ストレス管理戦略',
        'content_zh': (
            '壓力是生活的一部分，但學會有效管理壓力可以保護我們的身心健康。\n\n'
            '## 短期緩解技巧\n\n'
            '**深呼吸**\n慢慢吸氣 4 秒，屏住 4 秒，呼氣 4 秒。重複 5 次。\n\n'
            '**漸進式肌肉放鬆**\n從腳趾開始，逐步繃緊再放鬆每個肌肉群。\n\n'
            '**快速正念**\n花 1 分鐘，專注在你的五感所感受到的。\n\n'
            '## 長期管理策略\n\n'
            '**1. 時間管理**\n- 列出優先事項\n- 學會說「不」\n- 把大任務分成小步驟\n\n'
            '**2. 社交支持**\n- 與信任的人分享感受\n- 維持社交連結\n- 必要時尋求專業幫助\n\n'
            '**3. 健康生活方式**\n- 規律運動\n- 充足睡眠\n- 均衡飲食\n\n'
            '**4. 認知策略**\n- 區分可控和不可控的事物\n- 重新框架壓力情境\n- 練習感恩\n\n'
            '## 壓力的正面觀點\n\n'
            '適度的壓力可以提升表現和動機。關鍵在於找到健康的平衡點。'
        ),
        'content_en': (
            'Stress is a part of life, but learning to manage it effectively can protect your physical and mental health.\n\n'
            '## Short-term Relief Techniques\n\n'
            '**Deep Breathing**\nSlowly inhale for 4 seconds, hold for 4 seconds, exhale for 4 seconds. Repeat 5 times.\n\n'
            '**Progressive Muscle Relaxation**\nStarting from your toes, gradually tense and release each muscle group.\n\n'
            '**Quick Mindfulness**\nSpend 1 minute focusing on what your five senses are experiencing.\n\n'
            '## Long-term Management Strategies\n\n'
            '**1. Time Management**\n- List your priorities\n- Learn to say "no"\n- Break large tasks into smaller steps\n\n'
            '**2. Social Support**\n- Share your feelings with trusted people\n- Maintain social connections\n- Seek professional help when needed\n\n'
            '**3. Healthy Lifestyle**\n- Regular exercise\n- Adequate sleep\n- Balanced diet\n\n'
            '**4. Cognitive Strategies**\n- Distinguish between controllable and uncontrollable things\n- Reframe stressful situations\n- Practice gratitude\n\n'
            '## A Positive View of Stress\n\n'
            'Moderate stress can enhance performance and motivation. The key is finding a healthy balance.'
        ),
        'content_ja': (
            'ストレスは人生の一部ですが、効果的に管理することで心身の健康を守ることができます。\n\n'
            '## 短期的な緩和テクニック\n\n'
            '**深呼吸**\nゆっくり4秒吸い、4秒止め、4秒吐く。5回繰り返す。\n\n'
            '**漸進的筋弛緩法**\nつま先から始めて、各筋肉群を順番に緊張させてから弛緩させる。\n\n'
            '**クイックマインドフルネス**\n1分間、五感が感じていることに集中する。\n\n'
            '## 長期的な管理戦略\n\n'
            '**1. 時間管理**\n- 優先事項をリストアップ\n- 「ノー」と言うことを学ぶ\n- 大きなタスクを小さなステップに分ける\n\n'
            '**2. 社会的サポート**\n- 信頼できる人と気持ちを共有する\n- 社会的つながりを維持する\n- 必要に応じて専門家の助けを求める\n\n'
            '**3. 健康的なライフスタイル**\n- 定期的な運動\n- 十分な睡眠\n- バランスの取れた食事\n\n'
            '**4. 認知的戦略**\n- コントロールできることとできないことを区別する\n- ストレスフルな状況をリフレーミングする\n- 感謝を実践する\n\n'
            '## ストレスのポジティブな見方\n\n'
            '適度なストレスはパフォーマンスとモチベーションを高めます。鍵は健康的なバランスを見つけることです。'
        ),
        'category': 'stress',
        'reading_time': 5,
        'order': 8,
    },
]


def seed_articles(apps, schema_editor):
    PsychoArticle = apps.get_model('api', 'PsychoArticle')
    for article in ARTICLES:
        PsychoArticle.objects.get_or_create(
            title_en=article['title_en'],
            defaults=article,
        )


def unseed_articles(apps, schema_editor):
    PsychoArticle = apps.get_model('api', 'PsychoArticle')
    PsychoArticle.objects.filter(
        title_en__in=[a['title_en'] for a in ARTICLES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_wellness_features'),
    ]

    operations = [
        migrations.RunPython(seed_articles, unseed_articles),
    ]
