# Generated by Django 5.2.1 on 2026-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_seed_psycho_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychoarticle',
            name='source',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
