# Generated by Django 5.2.1 on 2026-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_fix_dead_article_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('note_create', 'Note Created'), ('note_update', 'Note Updated'), ('note_delete', 'Note Deleted'), ('note_restore', 'Note Restored'), ('note_permanent_delete', 'Note Permanently Deleted'), ('account_delete', 'Account Deleted'), ('export_data', 'Data Exported')], max_length=30),
        ),
    ]
