# Generated by Django 5.2.1 on 2026-02-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_credible_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ja', models.CharField(max_length=200)),
                ('description_zh', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_ja', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('cbt', 'CBT'), ('stress', 'Stress'), ('emotion', 'Emotion'), ('mindfulness', 'Mindfulness')], max_length=20)),
                ('icon_emoji', models.CharField(default='', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='psychoarticle',
            name='lesson_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychoarticle',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.course'),
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.psychoarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='WellnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('breathing', 'Breathing'), ('meditation', 'Meditation')], max_length=20)),
                ('exercise_name', models.CharField(max_length=100)),
                ('duration_seconds', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='wellness_user_completed')],
            },
        ),
    ]
