# Generated by Django 5.2.1 on 2026-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_sharedassessment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weeklysummary',
            index=models.Index(fields=['user', 'week_start'], name='weeklysummary_user_week'),
        ),
    ]
