# Generated by Django 5.1.15 on 2026-02-27 10:11

from django.db import migrations


def seed_existing_users(apps, schema_editor):
    """Set onboarding_completed=True and email_verified=True for all existing users."""
    User = apps.get_model('api', 'CustomUser')
    User.objects.all().update(onboarding_completed=True, email_verified=True)


def seed_subscription_plans(apps, schema_editor):
    """Create default Free, Pro, and Counselor subscription plans."""
    SubscriptionPlan = apps.get_model('api', 'SubscriptionPlan')
    plans = [
        {
            'name': 'Free',
            'tier': 'free',
            'price': 0,
            'currency': 'TWD',
            'features': {
                'notes_per_month': 30,
                'ai_analysis': True,
                'export_pdf': False,
                'counselor_chat': False,
                'push_notifications': False,
            },
        },
        {
            'name': 'Pro',
            'tier': 'pro',
            'price': 199,
            'currency': 'TWD',
            'features': {
                'notes_per_month': -1,
                'ai_analysis': True,
                'export_pdf': True,
                'counselor_chat': True,
                'push_notifications': True,
                'weekly_report': True,
            },
        },
        {
            'name': 'Counselor',
            'tier': 'counselor',
            'price': 499,
            'currency': 'TWD',
            'features': {
                'notes_per_month': -1,
                'ai_analysis': True,
                'export_pdf': True,
                'counselor_chat': True,
                'push_notifications': True,
                'weekly_report': True,
                'client_management': True,
                'shared_notes_access': True,
            },
        },
    ]
    for plan_data in plans:
        SubscriptionPlan.objects.get_or_create(
            tier=plan_data['tier'],
            defaults=plan_data,
        )


def reverse_seed(apps, schema_editor):
    """Reverse: delete seeded plans (users keep their flags)."""
    SubscriptionPlan = apps.get_model('api', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(tier__in=['free', 'pro', 'counselor']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_subscriptionplan_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_existing_users, migrations.RunPython.noop),
        migrations.RunPython(seed_subscription_plans, reverse_seed),
    ]
