# Generated by Django 5.2.1 on 2026-04-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_habit_habitlog_habit_habit_user_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict, help_text='Widget positions and settings: {"widgets": [{"id": "...", "x": 0, "y": 0, "w": 4, "h": 2, "enabled": true}]}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='dashboard_user')],
            },
        ),
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily_entries', 'Daily Entries'), ('avg_mood', 'Average Mood'), ('streak_days', 'Streak Days'), ('habit_completion', 'Habit Completion'), ('sleep_hours', 'Sleep Hours'), ('exercise_minutes', 'Exercise Minutes')], max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='usermetric_user_active')],
                'unique_together': {('user', 'metric_type')},
            },
        ),
    ]
