# Generated by Django 5.2.1 on 2026-04-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Post content (not encrypted)')),
                ('sentiment_score', models.FloatField(blank=True, help_text='AI-analyzed sentiment score', null=True)),
                ('category', models.CharField(blank=True, help_text='Auto-detected category: anxiety, stress, happiness, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='User can deactivate their own posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('hug', 'Hug'), ('support', 'Support'), ('heart', 'Heart')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.publicpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicpost',
            index=models.Index(fields=['-created_at'], name='publicpost_created'),
        ),
        migrations.AddIndex(
            model_name='publicpost',
            index=models.Index(fields=['user', '-created_at'], name='publicpost_user_created'),
        ),
        migrations.AddIndex(
            model_name='publicpost',
            index=models.Index(fields=['category', '-created_at'], name='publicpost_category_created'),
        ),
        migrations.AddIndex(
            model_name='publicpost',
            index=models.Index(fields=['is_active', '-created_at'], name='publicpost_active_created'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='reaction_post_type'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['user', '-created_at'], name='reaction_user_created'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'user', 'reaction_type')},
        ),
    ]
