# Generated by Django 5.2.1 on 2026-05-09 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_importjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment / Bullying'), ('hate', 'Hate speech'), ('self_harm', 'Self-harm / Suicide'), ('sexual', 'Sexual content'), ('violence', 'Violence / Threats'), ('misinfo', 'Misinformation'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed_kept', 'Reviewed — post kept'), ('reviewed_removed', 'Reviewed — post removed'), ('dismissed', 'Dismissed (invalid report)')], default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.publicpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='postreport_status_created'), models.Index(fields=['post', '-created_at'], name='postreport_post_created')],
                'unique_together': {('post', 'reporter')},
            },
        ),
    ]
