# Generated by Django 5.2.1 on 2026-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', '新訊息'), ('booking', '預約通知'), ('share', '日記分享'), ('system', '系統通知'), ('friend_request', '好友請求'), ('friend_accepted', '好友已接受'), ('friend_share', '好友分享日記'), ('friend_comment', '好友留言'), ('post_reaction', '社群貼文有人回應'), ('habit_reminder', '習慣打卡提醒')], max_length=20),
        ),
    ]
