# Generated by Django 5.2.1 on 2026-05-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_habit_reminder_periodic_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodnote',
            options={'ordering': ['-is_pinned', '-created_at', '-id']},
        ),
    ]
