# Generated by Django 5.2.12 on 2026-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_moodnote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='psychoarticle',
            name='category',
            field=models.CharField(choices=[('cbt', 'CBT'), ('mindfulness', 'Mindfulness'), ('emotion', 'Emotion'), ('stress', 'Stress'), ('sleep', 'Sleep')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='psychoarticle',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='counselorprofile',
            index=models.Index(fields=['status', '-created_at'], name='counselor_status_created'),
        ),
        migrations.AddIndex(
            model_name='psychoarticle',
            index=models.Index(fields=['is_published', 'category', 'order'], name='article_pub_cat_order'),
        ),
    ]
