# Generated by Django 5.2.12 on 2026-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_customuser_age_confirmed_13_plus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalstreak',
            name='freeze_tokens',
            field=models.IntegerField(default=1, help_text='Streak-freeze tokens available'),
        ),
        migrations.AddField(
            model_name='journalstreak',
            name='freeze_tokens_refilled_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
