# Generated by Django 5.2.12 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_journalstreak_freeze_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_band',
            field=models.CharField(blank=True, choices=[('18_plus', 'Adult (18+)'), ('13_17', 'Minor (13-17, guardian required)'), ('under_13', 'Under 13 (not allowed)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_ai_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_ai_training_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_consent_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
