# Generated by Django 5.2.12 on 2026-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_scrub_llm_template_leak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
