# Generated by Django 5.2.1 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_customuser_failed_login_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('zh-TW', '繁體中文'), ('en', 'English'), ('ja', '日本語')], default='zh-TW', help_text='Preferred UI language; the frontend adopts this on login.', max_length=10),
        ),
        migrations.AlterField(
            model_name='moodnote',
            name='search_text',
            field=models.TextField(blank=True, default='', help_text='Plaintext index (~30%% of length, capped at 200 chars) for DB-level search'),
        ),
    ]
